### ISSUE TITLE
(preload_world): unable to generate the end because of falling in the void

### ISSUE THREAD

**Issue by JulienTant** [Plagiatus/datapacks#11]
Hi,

When using the datapack in the end, i end up falling to my death... end of the story ^^ I was wondering if we could use `gamerule spectatorsGenerateChunks true` + `gamemode spectator` to solve the issue ? and teleporting at a more "normal" Y level

**Comment by JulienTant** [comment]
Another option could be to create a block at `~ -1 ~` before tp and removing it after all the rotations are done.

**Comment by Plagiatus** [comment]
I know of this problem where if you switch dimensions you start falling again and loose your "hovering" effect. I didn't get around to implement any fixes for this yet.

> if we could use gamerule spectatorsGenerateChunks true + gamemode spectator to solve the issue 

no, sadly we cannot do that, since the big steps are done using a end gateway, and spectators don't get teleported by end-gateways, we cannot do that. I've tried. A possible solution could be to set the player to creative for a short moment when inside the gateway and then back.

> Another option could be to create a block at ~ -1 ~ before tp and removing it after all the rotations are done.

also not an option, but this time because you cannot put a block at a negative position. best thing you could do is put it at ~ 0 ~.

------

I think the solution will be a combination of spectator mode / creative mode switches as well as an absolute height instead of a relative one.   
Thanks for reminding me of this issue, I'll try to improve this when I find the time.

**Comment by JulienTant** [comment]
Thanks for the 1.2 :) I close the ticket
