### ISSUE TITLE
Dealing with AFK players

### ISSUE THREAD

**Issue by ghost** [Plagiatus/datapacks#6]
Right now the function ignores players not in the overworld. you can easily test this with NBT tags but what if you set the percentage higher than 50% and you happen to be online with one or more afk players? You are basically forced to wait for the night to pass naturally or to lower the percentage disrupting whatever design you had in mind for this system. I thought about two solutions but I don't know how much they are feasible.

- Set a scoreboard for each online player counting the time they have been idle and flagging them with an afk tag if the value is > X.
  - This might help with movement detection https://www.youtube.com/watch?v=vzwaIvT3jjM
- Set an ideal percentage that is active when there are >= X players online but that proportionally decreases during low traffic.
  - Say for example I set 80% as percentage and find myself online with an AFK person, the result should be 1.6. I don't really know what criteria it uses to round down but if it does round down when the value is <= .5 then this is why I can't sleep when I'm playing with an AFK person

**Comment by Plagiatus** [comment]
Thank you for your suggestion. This datapack by design is in part made to accommodate for afk players, as those can't go to sleep or into the nether. Here it is in the responsibility of the admin to set the percentage to allow for a specific amount of afk players without interfering with the system. *Thus I won't incorporate a specific afk system into this datapack.* I can give you the instructions on how to combine this pack with Xisuma's mark afk players pack if you'd like, but I won't add it to this pack by default.

PS: It always rounds down. It could be 1.9999 and it'd still only require a single player to sleep.
